run:
  deadline: 30m
  concurrency: 2
  go: '1.18'
  allow-serial-runners: true
skip-dirs:
    - vendor
linters:
  disable-all: true
  enable:
    - LINTER_TO_RUN
  # Run with --fast=false for more extensive checks
  fast: false
  govet:
    # Report about shadowed variables.
    # Default: false
    check-shadowing: true
issues:
  exclude-rules:
    - path: tests/e2e
      linters:
        - revive
  #include:
  #  - EXC0002 # include "missing comments" issues from golint
  max-issues-per-linter: 0
  max-same-issues: 0
