run:
  deadline: 10m
skip-dirs:
    - vendor
linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
#    - errorlint
    - goconst
#    - gocyclo
    - gofmt
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
#    - interfacer
    - misspell
    - nakedret
#    - prealloc
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
  # Run with --fast=false for more extensive checks
  fast: false
  govet:
    # Report about shadowed variables.
    # Default: false
    check-shadowing: true
issues:
  exclude-rules:
    - path: tests/e2e
      linters:
        - revive
  #include:
  #  - EXC0002 # include "missing comments" issues from golint
  max-issues-per-linter: 0
  max-same-issues: 0
