# Netlify build instructions
[build]
    command = "npm install && hugo --minify --environment netlify"
    publish = "public/"

[build.environment]
    HUGO_VERSION = "0.113.0"
    GO_VERSION = "1.19.2"

# Standard Netlify redirects
[[redirects]]
    from = "https://kubernetes-sigs-cloud-provide-azure.netlify.app/*"
    to = "https://cloud-provider-azure.sigs.k8s.io/:splat"
    status = 301
    force = true

# HTTP-to-HTTPS rules
[[redirects]]
    from = "http://kubernetes-sigs-cloud-provide-azure.netlify.app/*"
    to = "https://cloud-provider-azure.sigs.k8s.io/:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://kubernetes-sigs-cloud-provide-azure.netlify.app/*"
    to = "http://cloud-provider-azure.sigs.k8s.io/:splat"
    status = 301
    force = true
