apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    tier: control-plane
    component: kube-scheduler
spec:
  hostNetwork: true
  containers:
    - name: kube-scheduler
      image: registry.k8s.io/hyperkube-amd64:v1.16.0-beta.1
      imagePullPolicy: IfNotPresent
      command: ["/hyperkube", "kube-scheduler"]
      args: ["--kubeconfig=/var/lib/kube-scheduler/kubeconfig", "--leader-elect=true", "--profiling=false", "--v=2"]
      volumeMounts:
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
        - name: var-lib-kube-scheduler
          mountPath: /var/lib/kube-scheduler
  volumes:
    - name: etc-kubernetes
      hostPath:
        path: /etc/kubernetes
    - name: var-lib-kube-scheduler
      hostPath:
        path: /var/lib/kube-scheduler
