// /*
// Copyright The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */

// Code generated by client-gen. DO NOT EDIT.
package fileshareclient

import (
	"context"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	armstorage "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage"
	"github.com/onsi/ginkgo/v2"
	"github.com/onsi/gomega"

	"sigs.k8s.io/cloud-provider-azure/pkg/azclient/utils"
)

var newResource *armstorage.FileShare
var (
	storageClientFactory *armstorage.ClientFactory
	storageaccountClient *armstorage.AccountsClient
	storageAccount       *armstorage.Account
)

func init() {
	additionalTestCases = func() {
		ginkgo.When("creation requests are raised", func() {
			ginkgo.It("should not return error", func(ctx context.Context) {
				resourceName = "akscitaccountfilesharetest"
				newResource, err := realClient.Create(ctx, resourceGroupName, accountName, resourceName, armstorage.FileShare{
					FileShareProperties: &armstorage.FileShareProperties{
						AccessTier:       to.Ptr(armstorage.ShareAccessTierCool),
						EnabledProtocols: to.Ptr(armstorage.EnabledProtocolsSMB),
					},
				}, nil)
				gomega.Expect(err).NotTo(gomega.HaveOccurred())
				gomega.Expect(newResource).NotTo(gomega.BeNil())
				gomega.Expect(*newResource.Name).To(gomega.Equal(resourceName))
			})
		})
		ginkgo.When("list requests are raised", func() {
			ginkgo.It("should not return error", func(ctx context.Context) {
				resourceList, err := realClient.List(ctx, resourceGroupName, accountName, nil)
				gomega.Expect(err).NotTo(gomega.HaveOccurred())
				gomega.Expect(resourceList).NotTo(gomega.BeNil())
				gomega.Expect(len(resourceList)).To(gomega.Equal(1))
				gomega.Expect(*resourceList[0].Name).To(gomega.Equal(resourceName))
			})
		})
		ginkgo.When("invalid list requests are raised", func() {
			ginkgo.It("should return error", func(ctx context.Context) {
				resourceList, err := realClient.List(ctx, resourceGroupName+"notfound", accountName, &armstorage.FileSharesClientListOptions{
					Expand: to.Ptr("snapshots"),
				})
				gomega.Expect(err).To(gomega.HaveOccurred())
				gomega.Expect(resourceList).To(gomega.BeNil())
			})
		})
		ginkgo.When("get requests are raised", func() {
			ginkgo.It("should not return error", func(ctx context.Context) {
				newResource, err := realClient.Get(ctx, resourceGroupName, accountName, resourceName, nil)
				gomega.Expect(err).NotTo(gomega.HaveOccurred())
				gomega.Expect(newResource).NotTo(gomega.BeNil())
			})
		})
		ginkgo.When("invalid get requests are raised", func() {
			ginkgo.It("should return 404 error", func(ctx context.Context) {
				newResource, err := realClient.Get(ctx, resourceGroupName, accountName, resourceName+"notfound", nil)
				gomega.Expect(err).To(gomega.HaveOccurred())
				gomega.Expect(newResource).To(gomega.BeNil())
			})
		})
	}

	beforeAllFunc = func(ctx context.Context) {
		storageClientFactory, err = armstorage.NewClientFactory(subscriptionID, recorder.TokenCredential(), &arm.ClientOptions{
			ClientOptions: policy.ClientOptions{
				Transport: recorder.HTTPClient(),
			},
		})
		gomega.Expect(err).NotTo(gomega.HaveOccurred())
		storageaccountClient = storageClientFactory.NewAccountsClient()
		newResource = &armstorage.FileShare{}
		accountName = "akscitacctsdktest"
		storageAccount, err := utils.NewPollerWrapper(storageaccountClient.BeginCreate(ctx, resourceGroupName, accountName, armstorage.AccountCreateParameters{
			Location: to.Ptr(location),
			Kind:     to.Ptr(armstorage.KindStorageV2),
			Properties: &armstorage.AccountPropertiesCreateParameters{
				DNSEndpointType:              to.Ptr(armstorage.DNSEndpointTypeStandard),
				DefaultToOAuthAuthentication: to.Ptr(false),
				AllowBlobPublicAccess:        to.Ptr(false),
				AllowCrossTenantReplication:  to.Ptr(false),
				IsHnsEnabled:                 to.Ptr(true),
				MinimumTLSVersion:            to.Ptr(armstorage.MinimumTLSVersionTLS12),
				AllowSharedKeyAccess:         to.Ptr(true),
				PublicNetworkAccess:          to.Ptr(armstorage.PublicNetworkAccessDisabled),
				IsLocalUserEnabled:           to.Ptr(true),
				LargeFileSharesState:         to.Ptr(armstorage.LargeFileSharesStateEnabled),
				IsSftpEnabled:                to.Ptr(true),
				EnableNfsV3:                  to.Ptr(true),
				EnableHTTPSTrafficOnly:       to.Ptr(true),
				NetworkRuleSet: &armstorage.NetworkRuleSet{
					Bypass:        to.Ptr(armstorage.BypassAzureServices),
					DefaultAction: to.Ptr(armstorage.DefaultActionDeny),
					IPRules:       []*armstorage.IPRule{},
				},
				Encryption: &armstorage.Encryption{
					RequireInfrastructureEncryption: to.Ptr(false),
					KeySource:                       to.Ptr(armstorage.KeySourceMicrosoftStorage),
					Services: &armstorage.EncryptionServices{
						File: &armstorage.EncryptionService{
							KeyType: to.Ptr(armstorage.KeyTypeAccount),
							Enabled: to.Ptr(true),
						},
						Blob: &armstorage.EncryptionService{
							KeyType: to.Ptr(armstorage.KeyTypeAccount),
							Enabled: to.Ptr(true),
						},
					},
				},
				AccessTier: to.Ptr(armstorage.AccessTierCool),
			},
			SKU: &armstorage.SKU{
				Name: to.Ptr(armstorage.SKUNameStandardLRS),
				Tier: to.Ptr(armstorage.SKUTierStandard),
			},
		}, nil)).WaitforPollerResp(ctx)
		gomega.Expect(err).NotTo(gomega.HaveOccurred())
		gomega.Expect(storageAccount).NotTo(gomega.BeNil())
		gomega.Expect(*storageAccount.Name).To(gomega.Equal(accountName))

	}
	afterAllFunc = func(ctx context.Context) {
		err := realClient.Delete(ctx, resourceGroupName, accountName, resourceName, nil)
		gomega.Expect(err).NotTo(gomega.HaveOccurred())
		_, err = storageaccountClient.Delete(ctx, resourceGroupName, accountName, nil)
		gomega.Expect(err).NotTo(gomega.HaveOccurred())
	}
}
