# Copyright 2026 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate references/INDEX.md from keyword annotations in patterns.md.

Usage:
    python3 scripts/gen_patterns_index.py

The script reads references/patterns.md, parses ## headers and their
<!-- keywords: ... --> comments, and writes references/INDEX.md with a
keyword lookup table and step_type defaults.
"""

from __future__ import annotations

import re
from pathlib import Path


def main() -> None:
    refs_dir = Path(__file__).resolve().parent.parent / "references"
    patterns_path = refs_dir / "patterns.md"
    index_path = refs_dir / "INDEX.md"

    lines = patterns_path.read_text().splitlines()

    # Parse sections: list of (header_name, keywords, start_line_1indexed)
    sections: list[tuple[str, str, int]] = []
    for i, line in enumerate(lines):
        m = re.match(r"^## (.+)$", line)
        if m:
            header = m.group(1)
            # Check if next line is a keyword comment
            keywords = ""
            if i + 1 < len(lines):
                km = re.match(r"^<!-- keywords:\s*(.+?)\s*-->$", lines[i + 1])
                if km:
                    keywords = km.group(1)
            sections.append((header, keywords, i + 1))  # 1-indexed

    # Compute line ranges
    section_ranges: list[tuple[str, str, int, int]] = []
    for idx, (header, keywords, start) in enumerate(sections):
        if idx + 1 < len(sections):
            end = sections[idx + 1][2] - 1  # line before next header
        else:
            end = len(lines)
        section_ranges.append((header, keywords, start, end))

    # Step type defaults mapping
    step_type_defaults = [
        ("k8s_create", "Namespace Ops, Deployment Ops, Service Ops"),
        ("k8s_update", "Service Ops"),
        ("k8s_delete", "Namespace Ops, Service Ops"),
        ("k8s_wait", "Service Ops, Deployment Ops"),
        ("az_create", "Public IP Ops, VNet/Subnet Ops"),
        ("az_read", "LB Verification, NSG Verification, PLS, VNet/Subnet Ops"),
        ("az_delete", "Public IP Ops, VNet/Subnet Ops"),
        ("az_wait", "LB Verification"),
        ("connectivity_check", "Connectivity Testing"),
        ("assertion", "LB Verification, NSG Verification, ETag/No-op Verification"),
        ("phase", "(no patterns needed)"),
    ]

    # Build INDEX.md
    out: list[str] = []
    out.append("<!-- Generated by scripts/gen_patterns_index.py — do not edit manually -->")
    out.append("# patterns.md Index")
    out.append("")
    out.append("Read this file first. Then use the line ranges below to read only the")
    out.append("relevant sections of `patterns.md` with offset and limit parameters.")
    out.append("")
    out.append("## Keyword Lookup")
    out.append("")
    out.append("| Keyword | Section | Lines |")
    out.append("|---|---|---|")
    for header, keywords, start, end in section_ranges:
        if keywords:
            out.append(f"| {keywords} | {header} | {start}–{end} |")
    out.append("")
    out.append("## Step Type Defaults")
    out.append("")
    out.append("When the step description has no clear keyword match, use these defaults:")
    out.append("")
    out.append("| step_type | Default sections |")
    out.append("|---|---|")
    for stype, defaults in step_type_defaults:
        out.append(f"| {stype} | {defaults} |")
    out.append("")
    out.append("## Resilience")
    out.append("")
    out.append("If the content at the given line range does not start with the expected `## `")
    out.append("header, the line numbers may be stale. Scan forward or backward for the nearest")
    out.append("`## ` header matching the section name, or re-read the full file.")
    out.append("")

    index_path.write_text("\n".join(out))
    print(f"Generated {index_path}")


if __name__ == "__main__":
    main()
