name: Discover Go modules
description: Discover Go modules and compute the highest Go version and go.sum paths
outputs:
  version:
    description: Highest Go version from go.mod files
    value: ${{ steps.discover.outputs.version }}
  modules:
    description: Newline-delimited list of module directories
    value: ${{ steps.discover.outputs.modules }}
  gosums:
    description: Newline-delimited list of go.sum paths
    value: ${{ steps.discover.outputs.gosums }}
runs:
  using: composite
  steps:
    - id: discover
      shell: bash
      run: |
        set -euo pipefail
        mapfile -t go_mods < <(git ls-files 'go.mod' '**/go.mod')
        if [ "${#go_mods[@]}" -eq 0 ]; then
          echo "No go.mod files found" >&2
          exit 1
        fi

        max=$(awk '$1=="go"{print $2}' "${go_mods[@]}" | sort -V | tail -n1)
        if [ -z "${max}" ]; then
          echo "No go directive found in go.mod files" >&2
          exit 1
        fi

        modules=()
        gosums=()
        for mod in "${go_mods[@]}"; do
          dir="$(dirname "$mod")"
          modules+=("${dir}")
          if [ -f "${dir}/go.sum" ]; then
            gosums+=("${dir}/go.sum")
          fi
        done

        mapfile -t modules < <(printf '%s\n' "${modules[@]}" | sort -u)
        mapfile -t gosums < <(printf '%s\n' "${gosums[@]}" | sort -u)

        {
          echo "version=${max}"
          echo "modules<<EOF"
          printf '%s\n' "${modules[@]}"
          echo "EOF"
          echo "gosums<<EOF"
          printf '%s\n' "${gosums[@]}"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
