apiVersion: v1
kind: Pod
metadata:
  name: azure-cloud-controller-manager
  namespace: kube-system
  labels:
    tier: control-plane
    component: azure-cloud-controller-manager
spec:
  hostNetwork: true
  containers:
    - name: azure-cloud-controller-manager
      image: mcr.microsoft.com/k8s/core/azure-cloud-controller-manager:v0.1.0
      imagePullPolicy: IfNotPresent
      command:
      - "cloud-controller-manager"
      args:
      - "--allocate-node-cidrs=true"
      - "--cloud-config=/etc/kubernetes/azure.json"
      - "--cloud-provider=azure"
      - "--cluster-cidr=10.244.0.0/16"
      - "--cluster-name=kubernetes"
      - "--configure-cloud-routes=true"
      - "--kubeconfig=/etc/kubernetes/kubeconfig"
      - "--leader-elect=true"
      - "--route-reconciliation-period=10s"
      - "--v=2"
      volumeMounts:
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
        - name: etc-ssl
          mountPath: /etc/ssl
          readOnly: true
        - name: msi
          mountPath: /var/lib/waagent/ManagedIdentity-Settings
          readOnly: true
  volumes:
    - name: etc-kubernetes
      hostPath:
        path: /etc/kubernetes
    - name: etc-ssl
      hostPath:
        path: /etc/ssl
    - name: msi
      hostPath:
        path: /var/lib/waagent/ManagedIdentity-Settings
