// /*
// Copyright The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */
//

// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -destination=./mock_repo.go -package=loadbalancer -copyright_file ../../../hack/boilerplate/boilerplate.generatego.txt -source=repo.go Repository
//

// Package loadbalancer is a generated GoMock package.
package loadbalancer

import (
	context "context"
	reflect "reflect"

	armnetwork "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v6"
	gomock "go.uber.org/mock/gomock"
	cache "sigs.k8s.io/cloud-provider-azure/pkg/cache"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateOrUpdate mocks base method.
func (m *MockRepository) CreateOrUpdate(ctx context.Context, resourceGroup string, resource *armnetwork.LoadBalancer) (*armnetwork.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdate", ctx, resourceGroup, resource)
	ret0, _ := ret[0].(*armnetwork.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdate indicates an expected call of CreateOrUpdate.
func (mr *MockRepositoryMockRecorder) CreateOrUpdate(ctx, resourceGroup, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdate", reflect.TypeOf((*MockRepository)(nil).CreateOrUpdate), ctx, resourceGroup, resource)
}

// CreateOrUpdateBackendPool mocks base method.
func (m *MockRepository) CreateOrUpdateBackendPool(ctx context.Context, resourceGroup, resourceName string, backendPool *armnetwork.BackendAddressPool) (*armnetwork.BackendAddressPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateBackendPool", ctx, resourceGroup, resourceName, backendPool)
	ret0, _ := ret[0].(*armnetwork.BackendAddressPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdateBackendPool indicates an expected call of CreateOrUpdateBackendPool.
func (mr *MockRepositoryMockRecorder) CreateOrUpdateBackendPool(ctx, resourceGroup, resourceName, backendPool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateBackendPool", reflect.TypeOf((*MockRepository)(nil).CreateOrUpdateBackendPool), ctx, resourceGroup, resourceName, backendPool)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, resourceGroup, resourceName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resourceGroup, resourceName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, resourceGroup, resourceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, resourceGroup, resourceName)
}

// DeleteBackendPool mocks base method.
func (m *MockRepository) DeleteBackendPool(ctx context.Context, resourceGroup, resourceName, backendPoolName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBackendPool", ctx, resourceGroup, resourceName, backendPoolName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBackendPool indicates an expected call of DeleteBackendPool.
func (mr *MockRepositoryMockRecorder) DeleteBackendPool(ctx, resourceGroup, resourceName, backendPoolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBackendPool", reflect.TypeOf((*MockRepository)(nil).DeleteBackendPool), ctx, resourceGroup, resourceName, backendPoolName)
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, resourceGroup, resourceName string, crt cache.AzureCacheReadType) (*armnetwork.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroup, resourceName, crt)
	ret0, _ := ret[0].(*armnetwork.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, resourceGroup, resourceName, crt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, resourceGroup, resourceName, crt)
}

// GetBackendPool mocks base method.
func (m *MockRepository) GetBackendPool(ctx context.Context, resourceGroup, resourceName, backendPoolName string) (*armnetwork.BackendAddressPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackendPool", ctx, resourceGroup, resourceName, backendPoolName)
	ret0, _ := ret[0].(*armnetwork.BackendAddressPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackendPool indicates an expected call of GetBackendPool.
func (mr *MockRepositoryMockRecorder) GetBackendPool(ctx, resourceGroup, resourceName, backendPoolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackendPool", reflect.TypeOf((*MockRepository)(nil).GetBackendPool), ctx, resourceGroup, resourceName, backendPoolName)
}

// ListByResourceGroup mocks base method.
func (m *MockRepository) ListByResourceGroup(ctx context.Context, resourceGroup string) ([]*armnetwork.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByResourceGroup", ctx, resourceGroup)
	ret0, _ := ret[0].([]*armnetwork.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByResourceGroup indicates an expected call of ListByResourceGroup.
func (mr *MockRepositoryMockRecorder) ListByResourceGroup(ctx, resourceGroup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByResourceGroup", reflect.TypeOf((*MockRepository)(nil).ListByResourceGroup), ctx, resourceGroup)
}

// MigrateToIPBased mocks base method.
func (m *MockRepository) MigrateToIPBased(ctx context.Context, resourceGroup, resourceName string, pools []*string) (*armnetwork.MigratedPools, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrateToIPBased", ctx, resourceGroup, resourceName, pools)
	ret0, _ := ret[0].(*armnetwork.MigratedPools)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MigrateToIPBased indicates an expected call of MigrateToIPBased.
func (mr *MockRepositoryMockRecorder) MigrateToIPBased(ctx, resourceGroup, resourceName, pools any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrateToIPBased", reflect.TypeOf((*MockRepository)(nil).MigrateToIPBased), ctx, resourceGroup, resourceName, pools)
}
