// Code generated by MockGen. DO NOT EDIT.
// Source: ./azure_loadbalancer_backendpool.go
//
// Generated by this command:
//
//	mockgen -destination=./azure_mock_loadbalancer_backendpool.go -source=./azure_loadbalancer_backendpool.go -package=provider BackendPool
//

// Package provider is a generated GoMock package.
package provider

import (
	context "context"
	reflect "reflect"

	armnetwork "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v6"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockBackendPool is a mock of BackendPool interface.
type MockBackendPool struct {
	ctrl     *gomock.Controller
	recorder *MockBackendPoolMockRecorder
	isgomock struct{}
}

// MockBackendPoolMockRecorder is the mock recorder for MockBackendPool.
type MockBackendPoolMockRecorder struct {
	mock *MockBackendPool
}

// NewMockBackendPool creates a new mock instance.
func NewMockBackendPool(ctrl *gomock.Controller) *MockBackendPool {
	mock := &MockBackendPool{ctrl: ctrl}
	mock.recorder = &MockBackendPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendPool) EXPECT() *MockBackendPoolMockRecorder {
	return m.recorder
}

// CleanupVMSetFromBackendPoolByCondition mocks base method.
func (m *MockBackendPool) CleanupVMSetFromBackendPoolByCondition(ctx context.Context, slb *armnetwork.LoadBalancer, service *v1.Service, nodes []*v1.Node, clusterName string, shouldRemoveVMSetFromSLB func(string) bool) (*armnetwork.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupVMSetFromBackendPoolByCondition", ctx, slb, service, nodes, clusterName, shouldRemoveVMSetFromSLB)
	ret0, _ := ret[0].(*armnetwork.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupVMSetFromBackendPoolByCondition indicates an expected call of CleanupVMSetFromBackendPoolByCondition.
func (mr *MockBackendPoolMockRecorder) CleanupVMSetFromBackendPoolByCondition(ctx, slb, service, nodes, clusterName, shouldRemoveVMSetFromSLB any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupVMSetFromBackendPoolByCondition", reflect.TypeOf((*MockBackendPool)(nil).CleanupVMSetFromBackendPoolByCondition), ctx, slb, service, nodes, clusterName, shouldRemoveVMSetFromSLB)
}

// EnsureHostsInPool mocks base method.
func (m *MockBackendPool) EnsureHostsInPool(ctx context.Context, service *v1.Service, nodes []*v1.Node, backendPoolID, vmSetName, clusterName, lbName string, backendPool *armnetwork.BackendAddressPool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureHostsInPool", ctx, service, nodes, backendPoolID, vmSetName, clusterName, lbName, backendPool)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureHostsInPool indicates an expected call of EnsureHostsInPool.
func (mr *MockBackendPoolMockRecorder) EnsureHostsInPool(ctx, service, nodes, backendPoolID, vmSetName, clusterName, lbName, backendPool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureHostsInPool", reflect.TypeOf((*MockBackendPool)(nil).EnsureHostsInPool), ctx, service, nodes, backendPoolID, vmSetName, clusterName, lbName, backendPool)
}

// GetBackendPrivateIPs mocks base method.
func (m *MockBackendPool) GetBackendPrivateIPs(ctx context.Context, clusterName string, service *v1.Service, lb *armnetwork.LoadBalancer) ([]string, []string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackendPrivateIPs", ctx, clusterName, service, lb)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].([]string)
	return ret0, ret1
}

// GetBackendPrivateIPs indicates an expected call of GetBackendPrivateIPs.
func (mr *MockBackendPoolMockRecorder) GetBackendPrivateIPs(ctx, clusterName, service, lb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackendPrivateIPs", reflect.TypeOf((*MockBackendPool)(nil).GetBackendPrivateIPs), ctx, clusterName, service, lb)
}

// ReconcileBackendPools mocks base method.
func (m *MockBackendPool) ReconcileBackendPools(ctx context.Context, clusterName string, service *v1.Service, lb *armnetwork.LoadBalancer) (bool, bool, *armnetwork.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileBackendPools", ctx, clusterName, service, lb)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(*armnetwork.LoadBalancer)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ReconcileBackendPools indicates an expected call of ReconcileBackendPools.
func (mr *MockBackendPoolMockRecorder) ReconcileBackendPools(ctx, clusterName, service, lb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileBackendPools", reflect.TypeOf((*MockBackendPool)(nil).ReconcileBackendPools), ctx, clusterName, service, lb)
}
