// /*
// Copyright The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */

// Code generated by client-gen. DO NOT EDIT.
package azclient

import (
	"sigs.k8s.io/cloud-provider-azure/pkg/azclient/availabilitysetclient"
	"sigs.k8s.io/cloud-provider-azure/pkg/azclient/deploymentclient"
	"sigs.k8s.io/cloud-provider-azure/pkg/azclient/diskclient"
	"sigs.k8s.io/cloud-provider-azure/pkg/azclient/interfaceclient"
	"sigs.k8s.io/cloud-provider-azure/pkg/azclient/loadbalancerclient"
	"sigs.k8s.io/cloud-provider-azure/pkg/azclient/managedclusterclient"
	"sigs.k8s.io/cloud-provider-azure/pkg/azclient/privateendpointclient"
	"sigs.k8s.io/cloud-provider-azure/pkg/azclient/privatelinkserviceclient"
	"sigs.k8s.io/cloud-provider-azure/pkg/azclient/privatezoneclient"
	"sigs.k8s.io/cloud-provider-azure/pkg/azclient/publicipaddressclient"
	"sigs.k8s.io/cloud-provider-azure/pkg/azclient/publicipprefixclient"
	"sigs.k8s.io/cloud-provider-azure/pkg/azclient/routetableclient"
	"sigs.k8s.io/cloud-provider-azure/pkg/azclient/securitygroupclient"
	"sigs.k8s.io/cloud-provider-azure/pkg/azclient/snapshotclient"
	"sigs.k8s.io/cloud-provider-azure/pkg/azclient/subnetclient"
	"sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualmachineclient"
	"sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualmachinescalesetclient"
	"sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualmachinescalesetvmclient"
)

type ClientFactory interface {
	GetavailabilitysetclientInterface() availabilitysetclient.Interface
	GetdeploymentclientInterface() deploymentclient.Interface
	GetdiskclientInterface() diskclient.Interface
	GetinterfaceclientInterface() interfaceclient.Interface
	GetloadbalancerclientInterface() loadbalancerclient.Interface
	GetmanagedclusterclientInterface() managedclusterclient.Interface
	GetprivateendpointclientInterface() privateendpointclient.Interface
	GetprivatelinkserviceclientInterface() privatelinkserviceclient.Interface
	GetprivatezoneclientInterface() privatezoneclient.Interface
	GetpublicipaddressclientInterface() publicipaddressclient.Interface
	GetpublicipprefixclientInterface() publicipprefixclient.Interface
	GetroutetableclientInterface() routetableclient.Interface
	GetsecuritygroupclientInterface() securitygroupclient.Interface
	GetsnapshotclientInterface() snapshotclient.Interface
	GetsubnetclientInterface() subnetclient.Interface
	GetvirtualmachineclientInterface() virtualmachineclient.Interface
	GetvirtualmachinescalesetclientInterface() virtualmachinescalesetclient.Interface
	GetvirtualmachinescalesetvmclientInterface() virtualmachinescalesetvmclient.Interface
}
