schedules:
- cron: "0 16 * * *"
  displayName: Daily GC
  branches:
    include:
    - master
  always: true

trigger: none

pr: none

pool: cloud-provider-azure-e2e-pool

variables:
- template: var-e2e.yml

stages:
  - stage: gc_stage
    dependsOn: []
    jobs:
    - job: gc_job
      timeoutInMinutes: 30
      steps:
        - bash: |
            export AZURE_SUBSCRIPTION_ID=$AZ_SUBSCRIPTION_ID
            export AZURE_TENANT_ID=$AZ_TENANT_ID

            .pipelines/scripts/daily-gc.sh
          displayName: gc aks and resource groups
          env:
            AZ_SUBSCRIPTION_ID: $(az.subscription_id)
            AZ_TENANT_ID: $(az.tenant_id)
