name: "Add Label to Pull Requests"
on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  add-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Add Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "tide/merge-method-squash"
