name: Code Lint - azclient

on: 
  push:
    branches: [ master, 'release-**' ]
    paths:
      - 'pkg/azclient/**'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master, 'release-**' ]
    paths:
      - 'pkg/azclient/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Lint:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Discover Go modules
        id: gomods
        uses: ./.github/actions/discover-go-modules
      - name: Setup Golang
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ steps.gomods.outputs.version }}
          check-latest: true
          cache-dependency-path: ${{ steps.gomods.outputs.gosums }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6.5.2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.64
          args: -v
          verify: true
